# UnchainedSouls Configuration File

# Soul drop amounts when killing entities
soul_drops:
  ZOMBIE: 5
  SKELETON: 3
  CREEPER: 10
  SPIDER: 4
  PLAYER: 50
  # Add more entity types as needed

# Costs for upgrading shadow stats
upgrade_costs:
  health: 50   # Cost in souls to upgrade health
  damage: 75   # Cost in souls to upgrade damage
  speed: 40    # Cost in souls to upgrade speed

# Evolution thresholds for shadows
evolution:
  threshold_1: 50   # Kills needed for first evolution
  threshold_2: 100  # Kills needed for second evolution

# Particle effect settings
particles:
  update_interval: 5   # Ticks between particle updates (1 tick = 1/20 sec)
  extraction_timeout: 2400  # Ticks before extraction expires (120 seconds)

# Customization options for shadows
customization:
  particle_effects:
    flames:
      name: "Flames"
      description: "Fiery particles surround your shadow"
      cost: 100
    smoke:
      name: "Smoke"
      description: "A dark, smoky aura"
      cost: 75
  titles:
    elite:
      name: "Elite"
      description: "Marks your shadow as a superior being"
      cost: 150
    guardian:
      name: "Guardian"
      description: "A protector’s title"
      cost: 120
  tags:
    warrior:
      name: "Warrior"
      description: "A fierce combatant"
      cost: 100
    void:
      name: "Void"
      description: "Touched by darkness"
      cost: 150
    phantom:
      name: "Phantom"
      description: "A ghostly presence"
      cost: 200

# Player soul storage (do not edit manually)
souls: {}
