name: UnchainedSouls
version: 1.0-SNAPSHOT
main: me.unchainedsouls.unchainedSoulsBeta.SoulsPlugin
api-version: '1.21'
author: Fsin
description: A shadow/pet system plugin where players can extract, evolve, and customize shadow pets from mobs.
website: https://github.com/Fsinas/unchained2025

commands:
  souls:
    description: Manage your soul balance
    usage: /<command> [balance|withdraw|deposit] [amount]
    permission: unchainedsouls.souls.use
  shadow:
    description: Manage your shadow pets
    usage: /<command> [summon|dismiss|customize|rename|tags] [args]
    permission: unchainedsouls.shadow.manage
  blackmarket:
    description: Open the black market
    usage: /<command>
    permission: unchainedsouls.blackmarket
  soulsadmin:
    description: Admin commands for soul management
    usage: /<command> <give|take|set> <player> <amount>
    permission: unchainedsouls.admin

permissions:
  unchainedsouls.souls.use:
    description: Allows use of soul management commands
    default: true
  unchainedsouls.shadow.manage:
    description: Allows management of shadow pets
    default: true
  unchainedsouls.blackmarket:
    description: Allows access to the black market
    default: true
  unchainedsouls.admin:
    description: Grants admin privileges for soul management
    default: op
